name: ♻️ Sync Labels

on:
  workflow_dispatch:

jobs:
  labels:
    name: ♻️ Sync labels
    runs-on: ubuntu-20.04
    steps:
      - name: ⤵️ Check out code from GitHub
        uses: actions/checkout@v3

      - name: 🚀 Run Label Sync
        uses: srealmoreno/label-sync-action@v1
        with:
          clean-labels: true
          token: ${{ secrets.GITHUBLABELING }}
          account-type: org
          config-file: |
            .github/labels.json
          repositories: |
            Ineduco/doc-faq-customer
            Ineduco/stk-base